In [2]:
import numpy as np
import pandas as pd
data = np.array([[3, 7],
                 [-4, -6],
                 [1, -1],
                 [7, 8],
                 [-4, -1],
                 [-3, -7]])
dataframe = pd.DataFrame(data, columns=['x1', 'x2'])

In [4]:
dataframe.describe()

             x1        x2
count  6.000000  6.000000
mean   0.000000  0.000000
std    4.472136  6.324555
min   -4.000000 -7.000000
25%   -3.750000 -4.750000
50%   -1.000000 -1.000000
75%    2.500000  5.000000
max    7.000000  8.000000

In [6]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
dataScaled = scaler.fit_transform(dataframe)

In [8]:
## Approach 1
c1 = dataframe.x1
c2 = dataframe.x2
np.cov(c1, c2)

array([[20., 25.],
       [25., 40.]])

In [12]:
## Approach 2
covarianceMatrix = dataframe.T @ dataframe / 5
covarianceMatrix

      x1    x2
x1  20.0  25.0
x2  25.0  40.0

In [ ]:
## Approach 3
np.sum(c1 * c2)/5

In [14]:
eigenValues, eigenVectors = np.linalg.eig(covarianceMatrix)

In [16]:
eigenVectors.sort()

In [18]:
## PC1 - Contains the maximum information of the original two features that you have
PC1 = dataframe @ eigenVectors[:, 0]
## PC2
PC2 = dataframe @ eigenVectors[:, 1]